apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex5
  namespace: ex5-environment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ex5
  template:
    metadata:
      labels:
        app: ex5
    spec:
      containers:
      - name: ex5
        image: sicki/my-firstimage:latest
        ports:
        - containerPort: 8888